version: '3'

services:
  todo_crm:
    build:
      context: ../../
      dockerfile: docker/develop/Dockerfile
    volumes:
      - ../../src:/opt/app
    ports:
      - 8080:8080
    command: ['python', 'run_server.py']
